CREATE SEQUENCE IF NOT EXISTS foodme.dish_addition_id_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS foodme.order_dish_addition_id_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE foodme.dish_addition (
    id BIGINT NOT NULL PRIMARY KEY,
    name_en VARCHAR(255),
    name_am VARCHAR(255),
    name_ru VARCHAR(255),
    price DOUBLE PRECISION NOT NULL,
    dish_id BIGINT NOT NULL REFERENCES foodme.dish(id)
);

CREATE TABLE foodme.order_dish_addition (
    id BIGINT NOT NULL PRIMARY KEY,
    name_en VARCHAR(255),
    name_am VARCHAR(255),
    name_ru VARCHAR(255),
    price DOUBLE PRECISION NOT NULL,
    order_dish_id BIGINT NOT NULL REFERENCES foodme.order_dish(id)
);

CREATE INDEX idx_dish_addition_dish_id ON foodme.dish_addition(dish_id);
CREATE INDEX idx_order_dish_addition_order_dish_id ON foodme.order_dish_addition(order_dish_id);

INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (1,'Fries','Fries','Fries', 200.0, 615) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (2,'Gluten-Free Bun','Gluten-Free Bun','Gluten-Free Bun', 300.0, 615) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (3,'Truffle Oil','Truffle Oil','Truffle Oil', 200.0, 220) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (4,'Extra Sauce','Extra Sauce','Extra Sauce', 300.0, 187) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (5,'Mushrooms','Mushrooms','Mushrooms', 500.0, 187) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (6,'Bacon','Bacon','Bacon', 500.0, 187) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (7,'Fries','Fries','Fries', 300.0, 189) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (8,'Avocado','Avocado','Avocado', 300.0, 189) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (9,'Truffle Oil','Truffle Oil','Truffle Oil', 500.0, 73) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (10,'Double Patty','Double Patty','Double Patty', 200.0, 73) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (11,'Side Salad','Side Salad','Side Salad', 300.0, 73) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (12,'Fried Egg','Fried Egg','Fried Egg', 200.0, 235) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (13,'Sweet Potato Fries','Sweet Potato Fries','Sweet Potato Fries', 200.0, 235) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (14,'Garlic Butter','Garlic Butter','Garlic Butter', 200.0, 91) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (15,'Jalapenos','Jalapenos','Jalapenos', 200.0, 91) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (16,'Bacon','Bacon','Bacon', 500.0, 91) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (17,'Avocado','Avocado','Avocado', 500.0, 39) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (18,'Extra Cheese','Extra Cheese','Extra Cheese', 500.0, 94) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (19,'Mushrooms','Mushrooms','Mushrooms', 500.0, 94) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (20,'Jalapenos','Jalapenos','Jalapenos', 500.0, 133) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (21,'Extra Meat','Extra Meat','Extra Meat', 200.0, 133) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (22,'Extra Cheese','Extra Cheese','Extra Cheese', 200.0, 185) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (23,'Vegan Cheese','Vegan Cheese','Vegan Cheese', 300.0, 185) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (24,'Jalapenos','Jalapenos','Jalapenos', 500.0, 185) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (25,'Truffle Oil','Truffle Oil','Truffle Oil', 500.0, 216) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (26,'Extra Sauce','Extra Sauce','Extra Sauce', 200.0, 216) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (27,'Mushrooms','Mushrooms','Mushrooms', 500.0, 180) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (28,'Truffle Oil','Truffle Oil','Truffle Oil', 200.0, 180) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (29,'Avocado','Avocado','Avocado', 300.0, 180) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (30,'Onions','Onions','Onions', 200.0, 191) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (31,'Avocado','Avocado','Avocado', 200.0, 191) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (32,'Avocado','Avocado','Avocado', 200.0, 231) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (33,'Onions','Onions','Onions', 500.0, 239) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (34,'Fries','Fries','Fries', 500.0, 95) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (35,'Garlic Butter','Garlic Butter','Garlic Butter', 200.0, 95) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (36,'Vegan Cheese','Vegan Cheese','Vegan Cheese', 200.0, 95) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (37,'Fried Egg','Fried Egg','Fried Egg', 500.0, 78) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (38,'Bacon','Bacon','Bacon', 300.0, 78) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (39,'Garlic Butter','Garlic Butter','Garlic Butter', 500.0, 78) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (40,'Mushrooms','Mushrooms','Mushrooms', 500.0, 82) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (41,'Fried Egg','Fried Egg','Fried Egg', 500.0, 82) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (42,'Extra Meat','Extra Meat','Extra Meat', 300.0, 82) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (43,'Mushrooms','Mushrooms','Mushrooms', 500.0, 617) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (44,'Jalapenos','Jalapenos','Jalapenos', 500.0, 114) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (45,'Extra Sauce','Extra Sauce','Extra Sauce', 500.0, 72) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (46,'Side Salad','Side Salad','Side Salad', 500.0, 72) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (47,'Mushrooms','Mushrooms','Mushrooms', 200.0, 72) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (48,'Vegan Cheese','Vegan Cheese','Vegan Cheese', 200.0, 193) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (49,'Onions','Onions','Onions', 200.0, 193) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (50,'Mushrooms','Mushrooms','Mushrooms', 300.0, 44) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (51,'Side Salad','Side Salad','Side Salad', 300.0, 44) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (52,'Onion Rings','Onion Rings','Onion Rings', 300.0, 81) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (53,'Bacon','Bacon','Bacon', 200.0, 81) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (54,'Sweet Potato Fries','Sweet Potato Fries','Sweet Potato Fries', 200.0, 236) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (55,'Truffle Oil','Truffle Oil','Truffle Oil', 300.0, 236) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (56,'Gluten-Free Bun','Gluten-Free Bun','Gluten-Free Bun', 200.0, 80) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (57,'Onions','Onions','Onions', 300.0, 80) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (58,'Side Salad','Side Salad','Side Salad', 200.0, 80) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (59,'Side Salad','Side Salad','Side Salad', 500.0, 190) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (60,'Sweet Potato Fries','Sweet Potato Fries','Sweet Potato Fries', 200.0, 190) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (61,'Spicy Sauce','Spicy Sauce','Spicy Sauce', 500.0, 123) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (62,'Bacon','Bacon','Bacon', 200.0, 123) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (63,'Extra Meat','Extra Meat','Extra Meat', 200.0, 123) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (64,'Double Patty','Double Patty','Double Patty', 300.0, 388) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (65,'Gluten-Free Bun','Gluten-Free Bun','Gluten-Free Bun', 300.0, 388) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (66,'Sweet Potato Fries','Sweet Potato Fries','Sweet Potato Fries', 200.0, 233) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (67,'Avocado','Avocado','Avocado', 200.0, 233) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (68,'Double Patty','Double Patty','Double Patty', 200.0, 90) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (69,'Garlic Butter','Garlic Butter','Garlic Butter', 200.0, 90) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (70,'Onions','Onions','Onions', 500.0, 117) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (71,'Onion Rings','Onion Rings','Onion Rings', 200.0, 117) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (72,'Spicy Sauce','Spicy Sauce','Spicy Sauce', 300.0, 75) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (73,'Onion Rings','Onion Rings','Onion Rings', 200.0, 75) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (74,'Fries','Fries','Fries', 200.0, 75) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (75,'Vegan Cheese','Vegan Cheese','Vegan Cheese', 200.0, 126) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (76,'Truffle Oil','Truffle Oil','Truffle Oil', 300.0, 126) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (77,'Garlic Butter','Garlic Butter','Garlic Butter', 200.0, 62) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (78,'Mushrooms','Mushrooms','Mushrooms', 500.0, 62) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (79,'Fries','Fries','Fries', 500.0, 122) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (80,'Fries','Fries','Fries', 500.0, 122) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (81,'Vegan Cheese','Vegan Cheese','Vegan Cheese', 500.0, 384) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (82,'Onions','Onions','Onions', 300.0, 384) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (83,'Extra Cheese','Extra Cheese','Extra Cheese', 500.0, 384) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (84,'Double Patty','Double Patty','Double Patty', 200.0, 175) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (85,'Extra Sauce','Extra Sauce','Extra Sauce', 200.0, 175) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (86,'Onions','Onions','Onions', 200.0, 234) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (87,'Fried Egg','Fried Egg','Fried Egg', 500.0, 234) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (88,'Sour Cream','Sour Cream','Sour Cream', 500.0, 172) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (89,'Garlic Butter','Garlic Butter','Garlic Butter', 500.0, 89) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (90,'Spicy Sauce','Spicy Sauce','Spicy Sauce', 200.0, 38) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (91,'Bacon','Bacon','Bacon', 300.0, 38) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (92,'Avocado','Avocado','Avocado', 500.0, 238) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (93,'Truffle Oil','Truffle Oil','Truffle Oil', 500.0, 238) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (94,'Bacon','Bacon','Bacon', 200.0, 238) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (95,'Fries','Fries','Fries', 300.0, 240) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (96,'Onions','Onions','Onions', 200.0, 101) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (97,'Double Patty','Double Patty','Double Patty', 200.0, 101) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (98,'Mushrooms','Mushrooms','Mushrooms', 200.0, 101) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (99,'Fried Egg','Fried Egg','Fried Egg', 200.0, 167) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (100,'Sweet Potato Fries','Sweet Potato Fries','Sweet Potato Fries', 200.0, 167) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (101,'Fried Egg','Fried Egg','Fried Egg', 300.0, 379) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (102,'Side Salad','Side Salad','Side Salad', 300.0, 379) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (103,'Onions','Onions','Onions', 300.0, 379) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (104,'Fried Egg','Fried Egg','Fried Egg', 500.0, 130) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (105,'Vegan Cheese','Vegan Cheese','Vegan Cheese', 500.0, 130) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (106,'Jalapenos','Jalapenos','Jalapenos', 200.0, 130) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (107,'Onion Rings','Onion Rings','Onion Rings', 500.0, 125) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (108,'Vegan Cheese','Vegan Cheese','Vegan Cheese', 300.0, 176) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (109,'Vegan Cheese','Vegan Cheese','Vegan Cheese', 200.0, 74) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (110,'Sour Cream','Sour Cream','Sour Cream', 500.0, 74) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (111,'Extra Cheese','Extra Cheese','Extra Cheese', 500.0, 387) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (112,'Bacon','Bacon','Bacon', 500.0, 182) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (113,'Extra Cheese','Extra Cheese','Extra Cheese', 300.0, 383) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (114,'Jalapenos','Jalapenos','Jalapenos', 200.0, 113) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (115,'Onion Rings','Onion Rings','Onion Rings', 500.0, 71) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (116,'Mushrooms','Mushrooms','Mushrooms', 300.0, 71) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (117,'Onion Rings','Onion Rings','Onion Rings', 200.0, 391) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (118,'Garlic Butter','Garlic Butter','Garlic Butter', 300.0, 391) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (119,'Fries','Fries','Fries', 300.0, 391) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (120,'Garlic Butter','Garlic Butter','Garlic Butter', 500.0, 84) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (121,'Sweet Potato Fries','Sweet Potato Fries','Sweet Potato Fries', 500.0, 84) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (122,'Onion Rings','Onion Rings','Onion Rings', 200.0, 84) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (123,'Onions','Onions','Onions', 500.0, 100) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (124,'Garlic Butter','Garlic Butter','Garlic Butter', 200.0, 100) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (125,'Fried Egg','Fried Egg','Fried Egg', 500.0, 100) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (126,'Mushrooms','Mushrooms','Mushrooms', 200.0, 184) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (127,'Jalapenos','Jalapenos','Jalapenos', 200.0, 184) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (128,'Onion Rings','Onion Rings','Onion Rings', 200.0, 226) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (129,'Onion Rings','Onion Rings','Onion Rings', 200.0, 192) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (130,'Extra Meat','Extra Meat','Extra Meat', 500.0, 192) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (131,'Avocado','Avocado','Avocado', 500.0, 192) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (132,'Jalapenos','Jalapenos','Jalapenos', 500.0, 69) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (133,'Sweet Potato Fries','Sweet Potato Fries','Sweet Potato Fries', 200.0, 69) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (134,'Onion Rings','Onion Rings','Onion Rings', 500.0, 705) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (135,'Vegan Cheese','Vegan Cheese','Vegan Cheese', 200.0, 705) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (136,'Sour Cream','Sour Cream','Sour Cream', 500.0, 386) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (137,'Side Salad','Side Salad','Side Salad', 300.0, 174) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (138,'Spicy Sauce','Spicy Sauce','Spicy Sauce', 300.0, 174) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (139,'Extra Sauce','Extra Sauce','Extra Sauce', 500.0, 63) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (140,'Truffle Oil','Truffle Oil','Truffle Oil', 500.0, 63) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (141,'Spicy Sauce','Spicy Sauce','Spicy Sauce', 500.0, 63) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (142,'Extra Meat','Extra Meat','Extra Meat', 500.0, 619) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (143,'Double Patty','Double Patty','Double Patty', 300.0, 619) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (144,'Vegan Cheese','Vegan Cheese','Vegan Cheese', 500.0, 221) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (145,'Sweet Potato Fries','Sweet Potato Fries','Sweet Potato Fries', 300.0, 221) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (146,'Sweet Potato Fries','Sweet Potato Fries','Sweet Potato Fries', 300.0, 217) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (147,'Side Salad','Side Salad','Side Salad', 300.0, 217) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (148,'Extra Cheese','Extra Cheese','Extra Cheese', 500.0, 217) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (149,'Bacon','Bacon','Bacon', 500.0, 390) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (150,'Gluten-Free Bun','Gluten-Free Bun','Gluten-Free Bun', 500.0, 390) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (151,'Fries','Fries','Fries', 500.0, 390) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (152,'Side Salad','Side Salad','Side Salad', 500.0, 616) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (153,'Extra Meat','Extra Meat','Extra Meat', 200.0, 616) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (154,'Vegan Cheese','Vegan Cheese','Vegan Cheese', 200.0, 616) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (155,'Garlic Butter','Garlic Butter','Garlic Butter', 200.0, 139) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (156,'Avocado','Avocado','Avocado', 200.0, 139) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (157,'Gluten-Free Bun','Gluten-Free Bun','Gluten-Free Bun', 500.0, 139) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (158,'Extra Meat','Extra Meat','Extra Meat', 300.0, 232) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (159,'Fries','Fries','Fries', 200.0, 232) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (160,'Sour Cream','Sour Cream','Sour Cream', 200.0, 232) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (161,'Sweet Potato Fries','Sweet Potato Fries','Sweet Potato Fries', 500.0, 134) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (162,'Avocado','Avocado','Avocado', 500.0, 134) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (163,'Fried Egg','Fried Egg','Fried Egg', 300.0, 134) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (164,'Double Patty','Double Patty','Double Patty', 200.0, 92) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (165,'Vegan Cheese','Vegan Cheese','Vegan Cheese', 300.0, 92) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (166,'Spicy Sauce','Spicy Sauce','Spicy Sauce', 500.0, 92) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (167,'Fried Egg','Fried Egg','Fried Egg', 200.0, 230) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (168,'Side Salad','Side Salad','Side Salad', 300.0, 230) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (169,'Spicy Sauce','Spicy Sauce','Spicy Sauce', 500.0, 37) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (170,'Jalapenos','Jalapenos','Jalapenos', 200.0, 37) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (171,'Onions','Onions','Onions', 500.0, 138) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (172,'Sour Cream','Sour Cream','Sour Cream', 500.0, 61) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (173,'Truffle Oil','Truffle Oil','Truffle Oil', 200.0, 618) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (174,'Onion Rings','Onion Rings','Onion Rings', 500.0, 618) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (175,'Onion Rings','Onion Rings','Onion Rings', 200.0, 618) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (176,'Extra Cheese','Extra Cheese','Extra Cheese', 200.0, 222) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (177,'Onions','Onions','Onions', 200.0, 128) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (178,'Extra Sauce','Extra Sauce','Extra Sauce', 200.0, 128) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (179,'Extra Meat','Extra Meat','Extra Meat', 300.0, 105) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (180,'Gluten-Free Bun','Gluten-Free Bun','Gluten-Free Bun', 500.0, 105) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (181,'Bacon','Bacon','Bacon', 300.0, 105) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (182,'Jalapenos','Jalapenos','Jalapenos', 300.0, 45) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (183,'Garlic Butter','Garlic Butter','Garlic Butter', 200.0, 121) ON CONFLICT (id) DO NOTHING;
INSERT INTO foodme.dish_addition (id, name_en, name_am, name_ru, price, dish_id) VALUES (184,'Gluten-Free Bun','Gluten-Free Bun','Gluten-Free Bun', 500.0, 173) ON CONFLICT (id) DO NOTHING;
SELECT setval('foodme.dish_addition_id_seq', 185);
