apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    # Private hostname:port of the Prometheus service on Render.
    url: http://prometheus:10000
    isDefault: true
    editable: false

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:10000
    editable: false
